name: CI
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: 啟動電腦不關機
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Expand-Archive ngrok.zip
        ./ngrok/ngrok.exe authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
        Start-Process ./ngrok/ngrok.exe -ArgumentList "tcp --region ap 3389"
        echo "正在等候 IP 產生..."
        sleep 45
        $tunnels = Invoke-RestMethod http://localhost:4040/api/tunnels
        $publicUrl = $tunnels.tunnels[0].public_url
        Write-Host "================================"
        Write-Host "你的 IP 地址: $publicUrl"
        Write-Host "使用者: Administrator"
        Write-Host "================================"
        Write-Host "電腦現在開著，請直接連線！"
        sleep 21600
